### ISSUE TITLE
ipdb: IPv6 multipath is broken

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#418]
```
# python
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.routes.add({'dst': '1234::/64', 'multipath': [{'gateway': 'fe80::1', 'hops': 3}]}).commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 499, in commit
    raise error
pyroute2.netlink.exceptions.NetlinkError: (19, 'No such device')
>>> quit()
```

**Comment by svinota** [comment]
That's strange. Thanks, fixing.

**Comment by svinota** [comment]
One issue is fixed, but may come another :) pls check, if it works for you

**Comment by PaulSD** [comment]
Sorry, got busy with other things and this fell off my radar.
Partially fixed, but still not quite right:
```
# ip addr add 1234::100/64 dev eth0
# python
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.routes.add({'dst': '1235::/64', 'multipath': [{'gateway': '1234::1'}]}).commit()
>>> ipdb.routes.add({'dst': '1236::/64', 'multipath': [{'gateway': '1234::1'}, {'gateway': '1234::2'}]}).commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 509, in commit
    raise error
RuntimeError
>>> quit()
# ip -6 route
1235::/64 via 1234::1 dev eth0 metric 1024  pref medium
1236::/64 via 1234::1 dev eth0 metric 1024  pref medium
1236::/64 via 1234::2 dev eth0 metric 1024  pref medium
```

**Comment by svinota** [comment]
Looks like fixed meanwhile.

**Comment by svinota** [comment]
At least, can not reproduce. If you still have issues, pls reopen.
