### ISSUE TITLE
How to set preferred_lft when adding an address? 

### ISSUE THREAD

**Issue by fritzlab** [svinota/pyroute2#752]
There does not appear to be a way to set the lifetime of an IPv6 address, using `preferred_lft`. 

Here's what I'm trying to do with pyroute2:
```
with IPRoute() as ipr:
    ipr.link('add', ifname="dummy0", kind='dummy')
    idx = ipr.link_lookup(ifname="dummy0")[0]
    ipr.addr("add", index=idx, address="2001:db8::5678", mask=128, preferred_lft=0)
```

And the result (as we can see `preferred_lft` is not set):

```
$ ip addr show dev dummy0
303: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d2:37:57:9a:66:e1 brd ff:ff:ff:ff:ff:ff
    inet6 2001:db8::5678/128 scope global
       valid_lft forever preferred_lft forever.              <<<<  preferred lifetime not set 
```

Here's a working example using iproute2 directly, and we can see that the preferred lifetime is set as expected: 

```
$ ip link add dev dummy0 type dummy
$ ip addr add 2001:db8::5678/128 dev dummy0 preferred_lft 0

$ ip addr show dev dummy0
304: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether aa:03:fd:ae:3b:38 brd ff:ff:ff:ff:ff:ff
    inet6 2001:db8::5678/128 scope global deprecated
       valid_lft forever preferred_lft 0sec                <<<<  preferred lifetime set as intended 
```

**Comment by svinota** [comment]
Looks like a bug. Fixing.

**Comment by fritzlab** [comment]
@svinota how long into the fixing process are you?  I can dive into the code and try to get a PR together, but I don't want to duplicate efforts if you're already looking into it.

**Comment by svinota** [comment]
Should be fixed. You can use both `preferred` or `preferred_lft`, should work. As well as with `valid` or `valid_lft`.

**Comment by celebdor** [comment]
@svinota shoulldn't it be closed, now that it is fixed?

**Comment by svinota** [comment]
Yep.

**Comment by aha-young** [comment]
Hello, has this been resolved? Why am I still encountering this issue?

**Comment by svinota** [comment]
@aha-young thanks for the heads-up, the code wasn't covered with tests and got broken in updates.

Fixed again and added tests, see the PR. Will merge as soon as the CI is done.

**Comment by svinota** [comment]
Should be fixed on the master branch now, but I reopen just in case.

Will close again tonight, if no issues with the fix.

**Comment by aha-young** [comment]
> [@aha-young](https://github.com/aha-young) thanks for the heads-up, the code wasn't covered with tests and got broken in updates.
> 
> Fixed again and added tests, see the PR. Will merge as soon as the CI is done.

Thank you, the issue is resolved.
