### ISSUE TITLE
"mitogen" library should be added as a dependency in "pyroute2.core"

### ISSUE THREAD

**Issue by ralonsoh** [svinota/pyroute2#798]
Library "mitogen" is used in "pyroute2.core". It should be added as an installation dependency in the installation JSON file, under "install_requires" key.

In Neutron, when docs CI job is executed, all "pyroute2.core" modules are loaded and this library is not present.

Bug: https://bugs.launchpad.net/neutron/+bug/1928913

Snippet: http://paste.openstack.org/show/805473/

**Comment by mkorkalo** [comment]
I ran into the same issue.

**Comment by svinota** [comment]
Will be fixed tonight.

**Comment by ralonsoh** [comment]
Thanks a lot!

**Comment by svinota** [comment]
@ralonsoh the proper fix will take a bit more time.

The issue is that `pyroute2.core` must have no other deps than stdlib, even more strictly — a subset of stdlib.

The module causing this error is to be moved out of `pyroute2.core`, I try to fix that asap.

**Comment by svinota** [comment]
Should be fixed now. Will be in the next release on the weekend.

**Comment by ralonsoh** [comment]
Thank you!

**Comment by ralonsoh** [comment]
Hi @svinota:

We still have this problem because mitogen is not installed as a dependency of pyroute2 (not pyroute2-minimal). I think that is because of the project restructure. If (full)pyroute2 is installed, the main module will load all submodules (pr2modules) [1]. When ``pyroute2.nslink/pr2modules/remote/iproute.py`` is loaded, ``mitogen`` must be installed.

We have added a condition in our CI, forcing the mitogen library installation in this CI job: https://review.opendev.org/c/openstack/neutron/+/792077

Regards!

[1]https://github.com/svinota/pyroute2/blob/0.6.2/pyroute2/pyroute2/__init__.py#L68

**Comment by svinota** [comment]
Really sorry, I was sure that I have fixed the import, it must simply disable one class if mitogen not installed, but not raise any exception unless this class is directly addressed. Shortly speaking, mitogen must be optional.

So the bug is still here. Ok, fixing.

**Comment by svinota** [comment]
No, but wait. Why do you even load `pyroute2.nslink/pr2modules/remote/iproute.py` ? Neutron doesn't use it, IIRC?

`make docs` don't fail on that if there is no mitogen in the system, I have double-checked it right now.

**Comment by ralonsoh** [comment]
Right now Neutron installs mitogen when executing the "docs" tox job [1]. If you remove the mitogen library installation and force pyroute 0.6.2, the result is the same.

Output: http://paste.openstack.org/show/805732/

Changes in tox.ini: http://paste.openstack.org/show/805733/

[1]https://review.opendev.org/c/openstack/neutron/+/792077

**Comment by svinota** [comment]
Removed the mitogen dependency. Docs are still building ok.

```
(venv) neutron {master} $ git diff
diff --git a/tox.ini b/tox.ini
index 95e5db64d8..0d65b024fc 100644
--- a/tox.ini
+++ b/tox.ini
@@ -141,9 +141,6 @@ envdir = {toxworkdir}/docs
 deps =
   -c{env:UPPER_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
   -r{toxinidir}/doc/requirements.txt
-# NOTE(slaweq): mitogen is optional dependency of the pyroute2 and without it
-# our docs job is failing
-  mitogen>=0.2.9
 commands = sphinx-build -W -b html doc/source doc/build/html
 
 [testenv:pdf-docs]

(venv) neutron {master} $ tox -e docs
docs recreate: /home/test/Projects/neutron/.tox/docs
docs installdeps: -chttps://releases.openstack.org/constraints/upper/master, -r/home/test/Projects/neutron/doc/requirements.txt
docs develop-inst: /home/test/Projects/neutron
docs installed: alabaster==0.7.12,alembic==1.6.4,amqp==5.0.6,appdirs==1.4.4,attrs==21.2.0,Babel==2.9.1,beautifulsoup4==4.9.3,cachetools==4.2.2,certifi==2020.12.5,cffi==1.14.5,chardet==4.0.0,cliff==3.7.0,cmd2==1.5.0,colorama==0.4.4,cryptography==3.4.7,debtcollector==2.2.0,decorator==5.0.9,dnspython==1.16.0,docutils==0.16,dogpile.cache==1.1.3,dulwich==0.20.23,eventlet==0.31.0,extras==1.0.0,fasteners==0.16,fixtures==3.0.0,futurist==2.3.0,greenlet==1.1.0,httplib2==0.19.1,idna==2.10,imagesize==1.2.0,iso8601==0.1.14,Jinja2==3.0.1,jmespath==0.10.0,jsonpatch==1.32,jsonpointer==2.1,jsonschema==3.2.0,keystoneauth1==4.3.1,keystonemiddleware==9.2.0,kombu==5.1.0,linecache2==1.0.0,logutils==0.3.5,Mako==1.1.4,MarkupSafe==2.0.1,msgpack==1.0.2,munch==2.5.0,netaddr==0.8.0,netifaces==0.10.9,-e git+https://review.opendev.org/openstack/neutron@dd24662e5316a72fc5b9cbfe36bec1705ce2c505#egg=neutron,neutron-lib==2.11.0,openstackdocstheme==2.2.7,openstacksdk==0.57.0,os-client-config==2.1.0,os-ken==1.4.0,os-service-types==1.7.0,os-traits==2.5.0,os-vif==2.4.0,osc-lib==2.4.0,oslo.cache==2.7.0,oslo.concurrency==4.4.0,oslo.config==8.7.0,oslo.context==3.2.0,oslo.db==9.0.0,oslo.i18n==5.0.1,oslo.log==4.5.0,oslo.messaging==12.7.1,oslo.middleware==4.2.0,oslo.policy==3.8.0,oslo.privsep==2.5.0,oslo.reports==2.2.0,oslo.rootwrap==6.2.0,oslo.serialization==4.1.0,oslo.service==2.5.0,oslo.upgradecheck==1.3.0,oslo.utils==4.9.0,oslo.versionedobjects==2.4.0,oslotest==4.4.1,osprofiler==3.4.0,ovs==2.13.3,ovsdbapp==1.10.0,packaging==20.9,Paste==3.5.0,PasteDeploy==2.1.1,pbr==5.6.0,pecan==1.4.0,prettytable==0.7.2,psutil==5.8.0,pycadf==3.1.1,pycparser==2.20,Pygments==2.9.0,pyinotify==0.9.6,pyOpenSSL==20.0.1,pyparsing==2.4.7,pyperclip==1.8.2,pyroute2==0.5.19,pyrsistent==0.17.3,python-dateutil==2.8.1,python-designateclient==4.2.0,python-editor==1.0.4,python-keystoneclient==4.2.0,python-mimeparse==1.6.0,python-neutronclient==7.3.0,python-novaclient==17.4.0,python-subunit==1.4.0,pytz==2021.1,PyYAML==5.4.1,reno==3.3.0,repoze.lru==0.7,requests==2.25.1,requestsexceptions==1.4.0,rfc3986==1.5.0,Routes==2.5.1,setproctitle==1.2.2,simplejson==3.17.2,six==1.16.0,snowballstemmer==2.1.0,sortedcontainers==2.4.0,soupsieve==2.2.1,Sphinx==3.5.4,sphinx-feature-classification==1.1.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,SQLAlchemy==1.4.15,sqlalchemy-migrate==0.13.0,sqlparse==0.4.1,statsd==3.3.0,stevedore==3.3.0,Tempita==0.5.2,tenacity==6.3.1,testresources==2.0.1,testscenarios==0.5.0,testtools==2.4.0,tinyrpc==1.0.4,tooz==2.9.0,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.26.4,vine==5.0.0,voluptuous==0.12.1,waitress==2.0.0,wcwidth==0.2.5,WebOb==1.8.7,WebTest==2.0.35,wrapt==1.12.1,yappi==1.3.2
docs run-test-pre: PYTHONHASHSEED='689965651'
docs run-test: commands[0] | sphinx-build -W -b html doc/source doc/build/html
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/util/rst.py:56: DeprecationWarning: 'environmentfilter' is renamed to 'pass_environment', the old name will be removed in Jinja 3.1.
  def heading(env: Environment, text: str, level: int = 1) -> str:
Running Sphinx v3.5.4
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/jinja2glue.py:106: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  def warning(context: Dict, message: str, *args: Any, **kwargs: Any) -> str:
[openstackdocstheme] version: 2.2.7
[openstackdocstheme] connecting html-page-context event handler
loading pickled environment... done
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/jinja2glue.py:184: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  self.environment.globals['debug'] = contextfunction(pformat)
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/jinja2glue.py:186: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  self.environment.globals['accesskey'] = contextfunction(accesskey)
[openstackdocstheme] using theme from /home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/openstackdocstheme/theme
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/dhcp_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/dhcp_agent.conf.sample
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/dns/hash.py:23: DeprecationWarning: dns.hash module will be removed in future versions. Please use hashlib instead.
  warnings.warn(
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/dns/namedict.py:35: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  class NameDict(collections.MutableMapping):
WARNING:pyroute2:Beware of the coming changes in the project packaging
WARNING:pyroute2:https://github.com/svinota/pyroute2/discussions/786
/home/test/Projects/neutron/neutron/api/extensions.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/l3_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/l3_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/linuxbridge_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/linuxbridge_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/macvtap_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/macvtap_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/metadata_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/metadata_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/metering_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/metering_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/ml2_conf.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/ml2_conf.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/neutron.conf
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/neutron.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/openvswitch_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/openvswitch_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/ovn.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/ovn.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/sriov_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/sriov_agent.conf.sample
[oslo_policy.sphinxpolicygen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-policy-generator/policy.conf
[oslo_policy.sphinxpolicygen] writing sample policy to /home/test/Projects/neutron/doc/source/_static/neutron.policy.yaml.sample
ERROR:stevedore.extension:Could not load 'oslo_cache.etcd3gw': No module named 'etcd3gw'
ERROR:stevedore.extension:Could not load 'oslo_cache.memcache_pool': No module named 'memcache'
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 271 source files that are out of date
updating environment: 0 added, 12 changed, 0 removed
reading sources... [  8%] configuration/policy-sample
reading sources... [ 16%] configuration/samples/dhcp-agent
reading sources... [ 25%] configuration/samples/l3-agent
reading sources... [ 33%] configuration/samples/linuxbridge-agent
reading sources... [ 41%] configuration/samples/macvtap-agent
reading sources... [ 50%] configuration/samples/metadata-agent
reading sources... [ 58%] configuration/samples/metering-agent
reading sources... [ 66%] configuration/samples/ml2-conf
reading sources... [ 75%] configuration/samples/neutron
reading sources... [ 83%] configuration/samples/openvswitch-agent
reading sources... [ 91%] configuration/samples/ovn
reading sources... [100%] configuration/samples/sriov-agent

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  0%] _intro
writing output... [  0%] admin/archives/adv-config
writing output... [  1%] admin/archives/adv-features
writing output... [  1%] admin/archives/adv-operational-features
writing output... [  1%] admin/archives/arch
writing output... [  2%] admin/archives/auth
writing output... [  2%] admin/archives/config-agents
writing output... [  2%] admin/archives/config-identity
writing output... [  3%] admin/archives/config-plugins
writing output... [  3%] admin/archives/index
writing output... [  4%] admin/archives/introduction
writing output... [  4%] admin/archives/multi-dhcp-agents
writing output... [  4%] admin/archives/use
writing output... [  5%] admin/config
writing output... [  5%] admin/config-address-scopes
writing output... [  5%] admin/config-auto-allocation
writing output... [  6%] admin/config-az
writing output... [  6%] admin/config-bgp-dynamic-routing
writing output... [  7%] admin/config-bgp-floating-ip-over-l2-segmented-network
writing output... [  7%] admin/config-dhcp-ha
writing output... [  7%] admin/config-dns-int
writing output... [  8%] admin/config-dns-int-ext-serv
writing output... [  8%] admin/config-dns-res
writing output... [  8%] admin/config-dvr-ha-snat
writing output... [  9%] admin/config-fip-port-forwardings
writing output... [  9%] admin/config-ipam
writing output... [  9%] admin/config-ipv6
writing output... [ 10%] admin/config-logging
writing output... [ 10%] admin/config-macvtap
writing output... [ 11%] admin/config-ml2
writing output... [ 11%] admin/config-mtu
writing output... [ 11%] admin/config-network-segment-ranges
writing output... [ 12%] admin/config-ovs-dpdk
writing output... [ 12%] admin/config-ovs-offload
writing output... [ 12%] admin/config-ovsfwdriver
writing output... [ 13%] admin/config-qos
writing output... [ 13%] admin/config-qos-min-bw
writing output... [ 14%] admin/config-rbac
writing output... [ 14%] admin/config-routed-networks
writing output... [ 14%] admin/config-service-subnets
writing output... [ 15%] admin/config-services-agent
writing output... [ 15%] admin/config-sfc
writing output... [ 15%] admin/config-sriov
writing output... [ 16%] admin/config-subnet-onboard
writing output... [ 16%] admin/config-subnet-pools
writing output... [ 16%] admin/config-trunking
writing output... [ 17%] admin/config-wsgi
writing output... [ 17%] admin/deploy
writing output... [ 18%] admin/deploy-lb
writing output... [ 18%] admin/deploy-lb-ha-vrrp
writing output... [ 18%] admin/deploy-lb-provider
writing output... [ 19%] admin/deploy-lb-selfservice
writing output... [ 19%] admin/deploy-ovs
writing output... [ 19%] admin/deploy-ovs-ha-dvr
writing output... [ 20%] admin/deploy-ovs-ha-vrrp
writing output... [ 20%] admin/deploy-ovs-provider
writing output... [ 21%] admin/deploy-ovs-selfservice
writing output... [ 21%] admin/index
writing output... [ 21%] admin/intro
writing output... [ 22%] admin/intro-basic-networking
writing output... [ 22%] admin/intro-nat
writing output... [ 22%] admin/intro-network-components
writing output... [ 23%] admin/intro-network-namespaces
writing output... [ 23%] admin/intro-os-networking
writing output... [ 23%] admin/intro-overlay-protocols
writing output... [ 24%] admin/migration
writing output... [ 24%] admin/migration-classic-to-l3ha
writing output... [ 25%] admin/migration-database
writing output... [ 25%] admin/migration-nova-network-to-neutron
writing output... [ 25%] admin/misc
writing output... [ 26%] admin/misc-libvirt
writing output... [ 26%] admin/neutron_linuxbridge
writing output... [ 26%] admin/ops
writing output... [ 27%] admin/ops-ip-availability
writing output... [ 27%] admin/ops-quotas
writing output... [ 28%] admin/ops-resource-purge
writing output... [ 28%] admin/ops-resource-tags
writing output... [ 28%] admin/ovn/dpdk
writing output... [ 29%] admin/ovn/features
writing output... [ 29%] admin/ovn/igmp
writing output... [ 29%] admin/ovn/index
writing output... [ 30%] admin/ovn/ovn
writing output... [ 30%] admin/ovn/refarch/launch-instance-provider-network
writing output... [ 30%] admin/ovn/refarch/launch-instance-selfservice-network
writing output... [ 31%] admin/ovn/refarch/provider-networks
writing output... [ 31%] admin/ovn/refarch/refarch
writing output... [ 32%] admin/ovn/refarch/routers
writing output... [ 32%] admin/ovn/refarch/selfservice-networks
writing output... [ 32%] admin/ovn/routed_provider_networks
writing output... [ 33%] admin/ovn/router_availability_zones
writing output... [ 33%] admin/ovn/routing
writing output... [ 33%] admin/ovn/sriov
writing output... [ 34%] admin/ovn/troubleshooting
writing output... [ 34%] admin/ovn/tutorial
writing output... [ 35%] admin/vpnaas-scenario
writing output... [ 35%] cli/index
writing output... [ 35%] cli/neutron-debug
writing output... [ 36%] cli/neutron-sanity-check
writing output... [ 36%] cli/neutron-status
writing output... [ 36%] configuration/config
writing output... [ 37%] configuration/config-samples
writing output... [ 37%] configuration/dhcp-agent
writing output... [ 38%] configuration/index
writing output... [ 38%] configuration/l3-agent
writing output... [ 38%] configuration/linuxbridge-agent
writing output... [ 39%] configuration/macvtap-agent
writing output... [ 39%] configuration/metadata-agent
writing output... [ 39%] configuration/metering-agent
writing output... [ 40%] configuration/ml2-conf
writing output... [ 40%] configuration/neutron
writing output... [ 40%] configuration/openvswitch-agent
writing output... [ 41%] configuration/ovn
writing output... [ 41%] configuration/policy
writing output... [ 42%] configuration/policy-sample
writing output... [ 42%] configuration/samples/dhcp-agent
writing output... [ 42%] configuration/samples/l3-agent
writing output... [ 43%] configuration/samples/linuxbridge-agent
writing output... [ 43%] configuration/samples/macvtap-agent
writing output... [ 43%] configuration/samples/metadata-agent
writing output... [ 44%] configuration/samples/metering-agent
writing output... [ 44%] configuration/samples/ml2-conf
writing output... [ 45%] configuration/samples/neutron
writing output... [ 45%] configuration/samples/openvswitch-agent
writing output... [ 45%] configuration/samples/ovn
writing output... [ 46%] configuration/samples/sriov-agent
writing output... [ 46%] configuration/sriov-agent
writing output... [ 46%] contributor/alembic_migrations
writing output... [ 47%] contributor/client_command_extensions
writing output... [ 47%] contributor/contribute
writing output... [ 47%] contributor/contributing
writing output... [ 48%] contributor/dashboards/index
writing output... [ 48%] contributor/development_environment
writing output... [ 49%] contributor/effective_neutron
writing output... [ 49%] contributor/index
writing output... [ 49%] contributor/internals/address_scopes
writing output... [ 50%] contributor/internals/agent_extensions
writing output... [ 50%] contributor/internals/api_extensions
writing output... [ 50%] contributor/internals/api_layer
writing output... [ 51%] contributor/internals/calling_ml2_plugin
writing output... [ 51%] contributor/internals/code_profiling
writing output... [ 52%] contributor/internals/db_layer
writing output... [ 52%] contributor/internals/db_models
writing output... [ 52%] contributor/internals/dns_order
writing output... [ 53%] contributor/internals/external_dns_integration
writing output... [ 53%] contributor/internals/i18n
writing output... [ 53%] contributor/internals/index
writing output... [ 54%] contributor/internals/l2_agent_extensions
writing output... [ 54%] contributor/internals/l2_agents
writing output... [ 54%] contributor/internals/l3_agent_extensions
writing output... [ 55%] contributor/internals/layer3
writing output... [ 55%] contributor/internals/linuxbridge_agent
writing output... [ 56%] contributor/internals/live_migration
writing output... [ 56%] contributor/internals/ml2_ext_manager
writing output... [ 56%] contributor/internals/network_ip_availability
writing output... [ 57%] contributor/internals/objects_usage
writing output... [ 57%] contributor/internals/openvswitch_agent
writing output... [ 57%] contributor/internals/openvswitch_firewall
writing output... [ 58%] contributor/internals/ovn/data_model
writing output... [ 58%] contributor/internals/ovn/database_consistency
writing output... [ 59%] contributor/internals/ovn/distributed_ovsdb_events
writing output... [ 59%] contributor/internals/ovn/index
writing output... [ 59%] contributor/internals/ovn/l3_ha_rescheduling
writing output... [ 60%] contributor/internals/ovn/loadbalancer
writing output... [ 60%] contributor/internals/ovn/metadata_api
writing output... [ 60%] contributor/internals/ovn/native_dhcp
writing output... [ 61%] contributor/internals/ovn/ovn_network_logging
writing output... [ 61%] contributor/internals/ovn/ovn_worker
writing output... [ 61%] contributor/internals/ovn/port_forwarding
writing output... [ 62%] contributor/internals/ovs_vhostuser
writing output... [ 62%] contributor/internals/plugin-api
writing output... [ 63%] contributor/internals/policy
writing output... [ 63%] contributor/internals/provisioning_blocks
writing output... [ 63%] contributor/internals/quality_of_service
writing output... [ 64%] contributor/internals/quota
writing output... [ 64%] contributor/internals/retries
writing output... [ 64%] contributor/internals/rpc_api
writing output... [ 65%] contributor/internals/rpc_callbacks
writing output... [ 65%] contributor/internals/security_group_api
writing output... [ 66%] contributor/internals/segments
writing output... [ 66%] contributor/internals/service_extensions
writing output... [ 66%] contributor/internals/services_and_agents
writing output... [ 67%] contributor/internals/sriov_nic_agent
writing output... [ 67%] contributor/internals/tag
writing output... [ 67%] contributor/internals/upgrade
writing output... [ 68%] contributor/modules
writing output... [ 68%] contributor/neutron_api
writing output... [ 69%] contributor/ovn/index
writing output... [ 69%] contributor/ovn/tools
writing output... [ 69%] contributor/ovn_vagrant/index
writing output... [ 70%] contributor/ovn_vagrant/prerequisites
writing output... [ 70%] contributor/ovn_vagrant/sparse-architecture
writing output... [ 70%] contributor/policies/blueprints
writing output... [ 71%] contributor/policies/bugs
writing output... [ 71%] contributor/policies/code-reviews
writing output... [ 71%] contributor/policies/contributor-onboarding
writing output... [ 72%] contributor/policies/gate-failure-triage
writing output... [ 72%] contributor/policies/gerrit-recheck
writing output... [ 73%] contributor/policies/index
writing output... [ 73%] contributor/policies/neutron-teams
writing output... [ 73%] contributor/policies/release-checklist
writing output... [ 74%] contributor/policies/thirdparty-ci
writing output... [ 74%] contributor/stadium/governance
writing output... [ 74%] contributor/stadium/guidelines
writing output... [ 75%] contributor/stadium/index
writing output... [ 75%] contributor/testing/ci_scenario_jobs
writing output... [ 76%] contributor/testing/coverage
writing output... [ 76%] contributor/testing/db_transient_failure_injection
writing output... [ 76%] contributor/testing/fullstack
writing output... [ 77%] contributor/testing/index
writing output... [ 77%] contributor/testing/ovn_devstack
writing output... [ 77%] contributor/testing/tempest
writing output... [ 78%] contributor/testing/template_model_sync_test
writing output... [ 78%] contributor/testing/testing
writing output... [ 78%] contributor/upgrade_checks
writing output... [ 79%] feature_classification/feature_classification_introduction
writing output... [ 79%] feature_classification/general_feature_support_matrix
writing output... [ 80%] feature_classification/index
writing output... [ 80%] feature_classification/provider_network_support_matrix
writing output... [ 80%] index
writing output... [ 81%] install/common/get-started-networking
writing output... [ 81%] install/compute-install-obs
writing output... [ 81%] install/compute-install-option1-obs
writing output... [ 82%] install/compute-install-option1-rdo
writing output... [ 82%] install/compute-install-option1-ubuntu
writing output... [ 83%] install/compute-install-option2-obs
writing output... [ 83%] install/compute-install-option2-rdo
writing output... [ 83%] install/compute-install-option2-ubuntu
writing output... [ 84%] install/compute-install-rdo
writing output... [ 84%] install/compute-install-ubuntu
writing output... [ 84%] install/concepts
writing output... [ 85%] install/controller-install-obs
writing output... [ 85%] install/controller-install-option1-obs
writing output... [ 85%] install/controller-install-option1-rdo
writing output... [ 86%] install/controller-install-option1-ubuntu
writing output... [ 86%] install/controller-install-option2-obs
writing output... [ 87%] install/controller-install-option2-rdo
writing output... [ 87%] install/controller-install-option2-ubuntu
writing output... [ 87%] install/controller-install-rdo
writing output... [ 88%] install/controller-install-ubuntu
writing output... [ 88%] install/environment-networking-compute-obs
writing output... [ 88%] install/environment-networking-compute-rdo
writing output... [ 89%] install/environment-networking-compute-ubuntu
writing output... [ 89%] install/environment-networking-controller-obs
writing output... [ 90%] install/environment-networking-controller-rdo
writing output... [ 90%] install/environment-networking-controller-ubuntu
writing output... [ 90%] install/environment-networking-obs
writing output... [ 91%] install/environment-networking-rdo
writing output... [ 91%] install/environment-networking-storage-cinder
writing output... [ 91%] install/environment-networking-ubuntu
writing output... [ 92%] install/environment-networking-verify-obs
writing output... [ 92%] install/environment-networking-verify-rdo
writing output... [ 92%] install/environment-networking-verify-ubuntu
writing output... [ 93%] install/index
writing output... [ 93%] install/install-obs
writing output... [ 94%] install/install-rdo
writing output... [ 94%] install/install-ubuntu
writing output... [ 94%] install/overview
writing output... [ 95%] install/ovn/index
writing output... [ 95%] install/ovn/manual_install
writing output... [ 95%] install/ovn/tripleo_install
writing output... [ 96%] install/shared/note_configuration_vary_by_distribution
writing output... [ 96%] install/verify
writing output... [ 97%] install/verify-option1
writing output... [ 97%] install/verify-option2
writing output... [ 97%] ovn/dhcp_opts
writing output... [ 98%] ovn/faq/index
writing output... [ 98%] ovn/gaps
writing output... [ 98%] ovn/index
writing output... [ 99%] ovn/migration
writing output... [ 99%] pdf-index
writing output... [100%] reference/rest-api

generating indices... genindex py-modindex [openstackdocstheme] could not determine last_updated for 'py-modindex'
done
writing additional pages... search done
copying images... [  1%] admin/archives/figures/vmware_nsx_ex1.png
copying images... [  2%] admin/archives/figures/vmware_nsx_ex2.png
copying images... [  4%] admin/figures/bgp-dynamic-routing-overview.png
copying images... [  5%] admin/figures/bgp-dynamic-routing-example1.png
copying images... [  7%] admin/figures/bgp-dynamic-routing-example2.png
copying images... [  8%] admin/figures/bgp-floating-ip-over-l2-segmented-network.png
copying images... [ 10%] admin/figures/demo_multiple_dhcp_agents.png
copying images... [ 11%] admin/figures/logging-framework.png
copying images... [ 13%] admin/figures/config-macvtap-compute1.png
copying images... [ 14%] admin/figures/config-macvtap-compute2.png
copying images... [ 15%] admin/figures/port-chain-architecture-diagram.png
copying images... [ 17%] admin/figures/port-chain-diagram.png
copying images... [ 18%] admin/figures/deploy-lb-ha-vrrp-overview.png
copying images... [ 20%] admin/figures/deploy-lb-ha-vrrp-compconn1.png
copying images... [ 21%] admin/figures/deploy-lb-provider-overview.png
copying images... [ 23%] admin/figures/deploy-lb-provider-compconn1.png
copying images... [ 24%] admin/figures/deploy-lb-provider-compconn2.png
copying images... [ 26%] admin/figures/deploy-lb-provider-flowns1.png
copying images... [ 27%] admin/figures/deploy-lb-provider-flowew1.png
copying images... [ 28%] admin/figures/deploy-lb-provider-flowew2.png
copying images... [ 30%] admin/figures/deploy-lb-selfservice-overview.png
copying images... [ 31%] admin/figures/deploy-lb-selfservice-compconn1.png
copying images... [ 33%] admin/figures/deploy-lb-selfservice-flowns1.png
copying images... [ 34%] admin/figures/deploy-lb-selfservice-flowns2.png
copying images... [ 36%] admin/figures/deploy-lb-selfservice-flowew1.png
copying images... [ 37%] admin/figures/deploy-lb-selfservice-flowew2.png
copying images... [ 39%] admin/figures/deploy-ovs-ha-dvr-overview.png
copying images... [ 40%] admin/figures/deploy-ovs-ha-dvr-compconn1.png
copying images... [ 42%] admin/figures/deploy-ovs-ha-dvr-flowns1.png
copying images... [ 43%] admin/figures/deploy-ovs-ha-dvr-flowns2.png
copying images... [ 44%] admin/figures/deploy-ovs-ha-dvr-flowew1.png
copying images... [ 46%] admin/figures/deploy-ovs-ha-vrrp-overview.png
copying images... [ 47%] admin/figures/deploy-ovs-ha-vrrp-compconn1.png
copying images... [ 49%] admin/figures/deploy-ovs-provider-overview.png
copying images... [ 50%] admin/figures/deploy-ovs-provider-compconn1.png
copying images... [ 52%] admin/figures/deploy-ovs-provider-compconn2.png
copying images... [ 53%] admin/figures/deploy-ovs-provider-flowns1.png
copying images... [ 55%] admin/figures/deploy-ovs-provider-flowew1.png
copying images... [ 56%] admin/figures/deploy-ovs-provider-flowew2.png
copying images... [ 57%] admin/figures/deploy-ovs-selfservice-overview.png
copying images... [ 59%] admin/figures/deploy-ovs-selfservice-compconn1.png
copying images... [ 60%] admin/figures/deploy-ovs-selfservice-flowns1.png
copying images... [ 62%] admin/figures/deploy-ovs-selfservice-flowns2.png
copying images... [ 63%] admin/figures/deploy-ovs-selfservice-flowew1.png
copying images... [ 65%] admin/figures/deploy-ovs-selfservice-flowew2.png
copying images... [ 66%] admin/figures/NetworkTypes.png
copying images... [ 68%] admin/ovn/refarch/figures/ovn-hw.png
copying images... [ 69%] admin/ovn/refarch/figures/ovn-services.png
copying images... [ 71%] admin/ovn/refarch/figures/ovn-architecture1.png
copying images... [ 72%] admin/ovn/refarch/figures/ovn-compute1.png
copying images... [ 73%] admin/ovn/figures/ovn-north-south.png
copying images... [ 75%] admin/ovn/figures/ovn-north-south-distributed-fip.png
copying images... [ 76%] admin/ovn/figures/ovn-l3ha-bfd.png
copying images... [ 78%] admin/ovn/figures/ovn-l3ha-bfd-3gw.png
copying images... [ 79%] admin/ovn/figures/ovn-l3ha-bfd-failover.png
copying images... [ 81%] admin/ovn/figures/ovn-east-west-3.png
copying images... [ 82%] admin/ovn/figures/ovn-east-west-2.png
copying images... [ 84%] contributor/internals/images/under-the-hood-scenario-1-ovs-network.png
copying images... [ 85%] contributor/internals/images/under-the-hood-scenario-1-ovs-netns.png
copying images... [ 86%] contributor/internals/images/live-mig.png
copying images... [ 88%] contributor/internals/images/live-mig-ovs-hybrid.png
copying images... [ 89%] contributor/internals/images/under-the-hood-scenario-1-ovs-compute.png
copying images... [ 91%] contributor/testing/images/fullstack_multinode_simulation.png
copying images... [ 92%] install/figures/networklayout.png
copying images... [ 94%] install/figures/hwreqs.png
copying images... [ 95%] install/figures/network1-services.png
copying images... [ 97%] install/figures/network2-services.png
copying images... [ 98%] install/ovn/figures/tripleo-ovn-arch.png
copying images... [100%] install/ovn/figures/ovn-initial-resources.png

copying downloadable files... [100%] ../_static/neutron.policy.yaml.sample

copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in doc/build/html.
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
  docs: commands succeeded
  congratulations :)
  ```

**Comment by ralonsoh** [comment]
You are installing pyroute2==0.5.19, from the logs provided, not 0.6.x.

**Comment by svinota** [comment]
Oops. Thanks, trying.

**Comment by svinota** [comment]
@ralonsoh same with fixed upper-constraints, checked that the pyroute2 version is 0.6.2

```
(venv) neutron {master} $ tox -r -e docs
docs create: /home/test/Projects/neutron/.tox/docs
docs installdeps: -cupper-constraints.txt, -r/home/test/Projects/neutron/doc/requirements.txt
docs develop-inst: /home/test/Projects/neutron
docs installed: alabaster==0.7.12,alembic==1.6.4,amqp==5.0.6,appdirs==1.4.4,attrs==21.2.0,Babel==2.9.1,beautifulsoup4==4.9.3,cachetools==4.2.2,certifi==2020.12.5,cffi==1.14.5,chardet==4.0.0,cliff==3.7.0,cmd2==1.5.0,colorama==0.4.4,cryptography==3.4.7,debtcollector==2.2.0,decorator==5.0.9,dnspython==1.16.0,docutils==0.16,dogpile.cache==1.1.3,dulwich==0.20.23,eventlet==0.31.0,extras==1.0.0,fasteners==0.16,fixtures==3.0.0,futurist==2.3.0,greenlet==1.1.0,httplib2==0.19.1,idna==2.10,imagesize==1.2.0,iso8601==0.1.14,Jinja2==3.0.1,jmespath==0.10.0,jsonpatch==1.32,jsonpointer==2.1,jsonschema==3.2.0,keystoneauth1==4.3.1,keystonemiddleware==9.2.0,kombu==5.1.0,linecache2==1.0.0,logutils==0.3.5,Mako==1.1.4,MarkupSafe==2.0.1,msgpack==1.0.2,munch==2.5.0,netaddr==0.8.0,netifaces==0.10.9,-e git+https://review.opendev.org/openstack/neutron@dd24662e5316a72fc5b9cbfe36bec1705ce2c505#egg=neutron,neutron-lib==2.11.0,openstackdocstheme==2.2.7,openstacksdk==0.57.0,os-client-config==2.1.0,os-ken==1.4.0,os-service-types==1.7.0,os-traits==2.5.0,os-vif==2.4.0,osc-lib==2.4.0,oslo.cache==2.7.0,oslo.concurrency==4.4.0,oslo.config==8.7.0,oslo.context==3.2.0,oslo.db==9.0.0,oslo.i18n==5.0.1,oslo.log==4.5.0,oslo.messaging==12.7.1,oslo.middleware==4.2.0,oslo.policy==3.8.0,oslo.privsep==2.5.0,oslo.reports==2.2.0,oslo.rootwrap==6.2.0,oslo.serialization==4.1.0,oslo.service==2.5.0,oslo.upgradecheck==1.3.0,oslo.utils==4.9.0,oslo.versionedobjects==2.4.0,oslotest==4.4.1,osprofiler==3.4.0,ovs==2.13.3,ovsdbapp==1.10.0,packaging==20.9,Paste==3.5.0,PasteDeploy==2.1.1,pbr==5.6.0,pecan==1.4.0,prettytable==0.7.2,psutil==5.8.0,pycadf==3.1.1,pycparser==2.20,Pygments==2.9.0,pyinotify==0.9.6,pyOpenSSL==20.0.1,pyparsing==2.4.7,pyperclip==1.8.2,pyroute2==0.6.2,pyroute2.core==0.6.2,pyroute2.ethtool==0.6.2,pyroute2.ipdb==0.6.2,pyroute2.ipset==0.6.2,pyroute2.ndb==0.6.2,pyroute2.nftables==0.6.2,pyroute2.nslink==0.6.2,pyrsistent==0.17.3,python-dateutil==2.8.1,python-designateclient==4.2.0,python-editor==1.0.4,python-keystoneclient==4.2.0,python-mimeparse==1.6.0,python-neutronclient==7.3.0,python-novaclient==17.4.0,python-subunit==1.4.0,pytz==2021.1,PyYAML==5.4.1,reno==3.3.0,repoze.lru==0.7,requests==2.25.1,requestsexceptions==1.4.0,rfc3986==1.5.0,Routes==2.5.1,setproctitle==1.2.2,simplejson==3.17.2,six==1.16.0,snowballstemmer==2.1.0,sortedcontainers==2.4.0,soupsieve==2.2.1,Sphinx==3.5.4,sphinx-feature-classification==1.1.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,SQLAlchemy==1.4.15,sqlalchemy-migrate==0.13.0,sqlparse==0.4.1,statsd==3.3.0,stevedore==3.3.0,Tempita==0.5.2,tenacity==6.3.1,testresources==2.0.1,testscenarios==0.5.0,testtools==2.4.0,tinyrpc==1.0.4,tooz==2.9.0,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.26.4,vine==5.0.0,voluptuous==0.12.1,waitress==2.0.0,wcwidth==0.2.5,WebOb==1.8.7,WebTest==2.0.35,wrapt==1.12.1,yappi==1.3.2
docs run-test-pre: PYTHONHASHSEED='1940483922'
docs run-test: commands[0] | sphinx-build -W -b html doc/source doc/build/html
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/util/rst.py:56: DeprecationWarning: 'environmentfilter' is renamed to 'pass_environment', the old name will be removed in Jinja 3.1.
  def heading(env: Environment, text: str, level: int = 1) -> str:
Running Sphinx v3.5.4
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/jinja2glue.py:106: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  def warning(context: Dict, message: str, *args: Any, **kwargs: Any) -> str:
[openstackdocstheme] version: 2.2.7
[openstackdocstheme] connecting html-page-context event handler
loading pickled environment... done
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/jinja2glue.py:184: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  self.environment.globals['debug'] = contextfunction(pformat)
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/sphinx/jinja2glue.py:186: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  self.environment.globals['accesskey'] = contextfunction(accesskey)
[openstackdocstheme] using theme from /home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/openstackdocstheme/theme
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/dhcp_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/dhcp_agent.conf.sample
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/dns/hash.py:23: DeprecationWarning: dns.hash module will be removed in future versions. Please use hashlib instead.
  warnings.warn(
/home/test/Projects/neutron/.tox/docs/lib/python3.9/site-packages/dns/namedict.py:35: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  class NameDict(collections.MutableMapping):
/home/test/Projects/neutron/neutron/api/extensions.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/l3_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/l3_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/linuxbridge_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/linuxbridge_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/macvtap_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/macvtap_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/metadata_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/metadata_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/metering_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/metering_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/ml2_conf.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/ml2_conf.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/neutron.conf
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/neutron.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/openvswitch_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/openvswitch_agent.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/ovn.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/ovn.conf.sample
[oslo_config.sphinxconfiggen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-config-generator/sriov_agent.ini
[oslo_config.sphinxconfiggen] writing sample configuration to /home/test/Projects/neutron/doc/source/_static/config-samples/sriov_agent.conf.sample
[oslo_policy.sphinxpolicygen] reading config generator instructions from /home/test/Projects/neutron/doc/source/../../etc/oslo-policy-generator/policy.conf
[oslo_policy.sphinxpolicygen] writing sample policy to /home/test/Projects/neutron/doc/source/_static/neutron.policy.yaml.sample
ERROR:stevedore.extension:Could not load 'oslo_cache.etcd3gw': No module named 'etcd3gw'
ERROR:stevedore.extension:Could not load 'oslo_cache.memcache_pool': No module named 'memcache'
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 271 source files that are out of date
updating environment: 0 added, 12 changed, 0 removed
reading sources... [  8%] configuration/policy-sample
reading sources... [ 16%] configuration/samples/dhcp-agent
reading sources... [ 25%] configuration/samples/l3-agent
reading sources... [ 33%] configuration/samples/linuxbridge-agent
reading sources... [ 41%] configuration/samples/macvtap-agent
reading sources... [ 50%] configuration/samples/metadata-agent
reading sources... [ 58%] configuration/samples/metering-agent
reading sources... [ 66%] configuration/samples/ml2-conf
reading sources... [ 75%] configuration/samples/neutron
reading sources... [ 83%] configuration/samples/openvswitch-agent
reading sources... [ 91%] configuration/samples/ovn
reading sources... [100%] configuration/samples/sriov-agent

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  0%] _intro
writing output... [  0%] admin/archives/adv-config
writing output... [  1%] admin/archives/adv-features
writing output... [  1%] admin/archives/adv-operational-features
writing output... [  1%] admin/archives/arch
writing output... [  2%] admin/archives/auth
writing output... [  2%] admin/archives/config-agents
writing output... [  2%] admin/archives/config-identity
writing output... [  3%] admin/archives/config-plugins
writing output... [  3%] admin/archives/index
writing output... [  4%] admin/archives/introduction
writing output... [  4%] admin/archives/multi-dhcp-agents
writing output... [  4%] admin/archives/use
writing output... [  5%] admin/config
writing output... [  5%] admin/config-address-scopes
writing output... [  5%] admin/config-auto-allocation
writing output... [  6%] admin/config-az
writing output... [  6%] admin/config-bgp-dynamic-routing
writing output... [  7%] admin/config-bgp-floating-ip-over-l2-segmented-network
writing output... [  7%] admin/config-dhcp-ha
writing output... [  7%] admin/config-dns-int
writing output... [  8%] admin/config-dns-int-ext-serv
writing output... [  8%] admin/config-dns-res
writing output... [  8%] admin/config-dvr-ha-snat
writing output... [  9%] admin/config-fip-port-forwardings
writing output... [  9%] admin/config-ipam
writing output... [  9%] admin/config-ipv6
writing output... [ 10%] admin/config-logging
writing output... [ 10%] admin/config-macvtap
writing output... [ 11%] admin/config-ml2
writing output... [ 11%] admin/config-mtu
writing output... [ 11%] admin/config-network-segment-ranges
writing output... [ 12%] admin/config-ovs-dpdk
writing output... [ 12%] admin/config-ovs-offload
writing output... [ 12%] admin/config-ovsfwdriver
writing output... [ 13%] admin/config-qos
writing output... [ 13%] admin/config-qos-min-bw
writing output... [ 14%] admin/config-rbac
writing output... [ 14%] admin/config-routed-networks
writing output... [ 14%] admin/config-service-subnets
writing output... [ 15%] admin/config-services-agent
writing output... [ 15%] admin/config-sfc
writing output... [ 15%] admin/config-sriov
writing output... [ 16%] admin/config-subnet-onboard
writing output... [ 16%] admin/config-subnet-pools
writing output... [ 16%] admin/config-trunking
writing output... [ 17%] admin/config-wsgi
writing output... [ 17%] admin/deploy
writing output... [ 18%] admin/deploy-lb
writing output... [ 18%] admin/deploy-lb-ha-vrrp
writing output... [ 18%] admin/deploy-lb-provider
writing output... [ 19%] admin/deploy-lb-selfservice
writing output... [ 19%] admin/deploy-ovs
writing output... [ 19%] admin/deploy-ovs-ha-dvr
writing output... [ 20%] admin/deploy-ovs-ha-vrrp
writing output... [ 20%] admin/deploy-ovs-provider
writing output... [ 21%] admin/deploy-ovs-selfservice
writing output... [ 21%] admin/index
writing output... [ 21%] admin/intro
writing output... [ 22%] admin/intro-basic-networking
writing output... [ 22%] admin/intro-nat
writing output... [ 22%] admin/intro-network-components
writing output... [ 23%] admin/intro-network-namespaces
writing output... [ 23%] admin/intro-os-networking
writing output... [ 23%] admin/intro-overlay-protocols
writing output... [ 24%] admin/migration
writing output... [ 24%] admin/migration-classic-to-l3ha
writing output... [ 25%] admin/migration-database
writing output... [ 25%] admin/migration-nova-network-to-neutron
writing output... [ 25%] admin/misc
writing output... [ 26%] admin/misc-libvirt
writing output... [ 26%] admin/neutron_linuxbridge
writing output... [ 26%] admin/ops
writing output... [ 27%] admin/ops-ip-availability
writing output... [ 27%] admin/ops-quotas
writing output... [ 28%] admin/ops-resource-purge
writing output... [ 28%] admin/ops-resource-tags
writing output... [ 28%] admin/ovn/dpdk
writing output... [ 29%] admin/ovn/features
writing output... [ 29%] admin/ovn/igmp
writing output... [ 29%] admin/ovn/index
writing output... [ 30%] admin/ovn/ovn
writing output... [ 30%] admin/ovn/refarch/launch-instance-provider-network
writing output... [ 30%] admin/ovn/refarch/launch-instance-selfservice-network
writing output... [ 31%] admin/ovn/refarch/provider-networks
writing output... [ 31%] admin/ovn/refarch/refarch
writing output... [ 32%] admin/ovn/refarch/routers
writing output... [ 32%] admin/ovn/refarch/selfservice-networks
writing output... [ 32%] admin/ovn/routed_provider_networks
writing output... [ 33%] admin/ovn/router_availability_zones
writing output... [ 33%] admin/ovn/routing
writing output... [ 33%] admin/ovn/sriov
writing output... [ 34%] admin/ovn/troubleshooting
writing output... [ 34%] admin/ovn/tutorial
writing output... [ 35%] admin/vpnaas-scenario
writing output... [ 35%] cli/index
writing output... [ 35%] cli/neutron-debug
writing output... [ 36%] cli/neutron-sanity-check
writing output... [ 36%] cli/neutron-status
writing output... [ 36%] configuration/config
writing output... [ 37%] configuration/config-samples
writing output... [ 37%] configuration/dhcp-agent
writing output... [ 38%] configuration/index
writing output... [ 38%] configuration/l3-agent
writing output... [ 38%] configuration/linuxbridge-agent
writing output... [ 39%] configuration/macvtap-agent
writing output... [ 39%] configuration/metadata-agent
writing output... [ 39%] configuration/metering-agent
writing output... [ 40%] configuration/ml2-conf
writing output... [ 40%] configuration/neutron
writing output... [ 40%] configuration/openvswitch-agent
writing output... [ 41%] configuration/ovn
writing output... [ 41%] configuration/policy
writing output... [ 42%] configuration/policy-sample
writing output... [ 42%] configuration/samples/dhcp-agent
writing output... [ 42%] configuration/samples/l3-agent
writing output... [ 43%] configuration/samples/linuxbridge-agent
writing output... [ 43%] configuration/samples/macvtap-agent
writing output... [ 43%] configuration/samples/metadata-agent
writing output... [ 44%] configuration/samples/metering-agent
writing output... [ 44%] configuration/samples/ml2-conf
writing output... [ 45%] configuration/samples/neutron
writing output... [ 45%] configuration/samples/openvswitch-agent
writing output... [ 45%] configuration/samples/ovn
writing output... [ 46%] configuration/samples/sriov-agent
writing output... [ 46%] configuration/sriov-agent
writing output... [ 46%] contributor/alembic_migrations
writing output... [ 47%] contributor/client_command_extensions
writing output... [ 47%] contributor/contribute
writing output... [ 47%] contributor/contributing
writing output... [ 48%] contributor/dashboards/index
writing output... [ 48%] contributor/development_environment
writing output... [ 49%] contributor/effective_neutron
writing output... [ 49%] contributor/index
writing output... [ 49%] contributor/internals/address_scopes
writing output... [ 50%] contributor/internals/agent_extensions
writing output... [ 50%] contributor/internals/api_extensions
writing output... [ 50%] contributor/internals/api_layer
writing output... [ 51%] contributor/internals/calling_ml2_plugin
writing output... [ 51%] contributor/internals/code_profiling
writing output... [ 52%] contributor/internals/db_layer
writing output... [ 52%] contributor/internals/db_models
writing output... [ 52%] contributor/internals/dns_order
writing output... [ 53%] contributor/internals/external_dns_integration
writing output... [ 53%] contributor/internals/i18n
writing output... [ 53%] contributor/internals/index
writing output... [ 54%] contributor/internals/l2_agent_extensions
writing output... [ 54%] contributor/internals/l2_agents
writing output... [ 54%] contributor/internals/l3_agent_extensions
writing output... [ 55%] contributor/internals/layer3
writing output... [ 55%] contributor/internals/linuxbridge_agent
writing output... [ 56%] contributor/internals/live_migration
writing output... [ 56%] contributor/internals/ml2_ext_manager
writing output... [ 56%] contributor/internals/network_ip_availability
writing output... [ 57%] contributor/internals/objects_usage
writing output... [ 57%] contributor/internals/openvswitch_agent
writing output... [ 57%] contributor/internals/openvswitch_firewall
writing output... [ 58%] contributor/internals/ovn/data_model
writing output... [ 58%] contributor/internals/ovn/database_consistency
writing output... [ 59%] contributor/internals/ovn/distributed_ovsdb_events
writing output... [ 59%] contributor/internals/ovn/index
writing output... [ 59%] contributor/internals/ovn/l3_ha_rescheduling
writing output... [ 60%] contributor/internals/ovn/loadbalancer
writing output... [ 60%] contributor/internals/ovn/metadata_api
writing output... [ 60%] contributor/internals/ovn/native_dhcp
writing output... [ 61%] contributor/internals/ovn/ovn_network_logging
writing output... [ 61%] contributor/internals/ovn/ovn_worker
writing output... [ 61%] contributor/internals/ovn/port_forwarding
writing output... [ 62%] contributor/internals/ovs_vhostuser
writing output... [ 62%] contributor/internals/plugin-api
writing output... [ 63%] contributor/internals/policy
writing output... [ 63%] contributor/internals/provisioning_blocks
writing output... [ 63%] contributor/internals/quality_of_service
writing output... [ 64%] contributor/internals/quota
writing output... [ 64%] contributor/internals/retries
writing output... [ 64%] contributor/internals/rpc_api
writing output... [ 65%] contributor/internals/rpc_callbacks
writing output... [ 65%] contributor/internals/security_group_api
writing output... [ 66%] contributor/internals/segments
writing output... [ 66%] contributor/internals/service_extensions
writing output... [ 66%] contributor/internals/services_and_agents
writing output... [ 67%] contributor/internals/sriov_nic_agent
writing output... [ 67%] contributor/internals/tag
writing output... [ 67%] contributor/internals/upgrade
writing output... [ 68%] contributor/modules
writing output... [ 68%] contributor/neutron_api
writing output... [ 69%] contributor/ovn/index
writing output... [ 69%] contributor/ovn/tools
writing output... [ 69%] contributor/ovn_vagrant/index
writing output... [ 70%] contributor/ovn_vagrant/prerequisites
writing output... [ 70%] contributor/ovn_vagrant/sparse-architecture
writing output... [ 70%] contributor/policies/blueprints
writing output... [ 71%] contributor/policies/bugs
writing output... [ 71%] contributor/policies/code-reviews
writing output... [ 71%] contributor/policies/contributor-onboarding
writing output... [ 72%] contributor/policies/gate-failure-triage
writing output... [ 72%] contributor/policies/gerrit-recheck
writing output... [ 73%] contributor/policies/index
writing output... [ 73%] contributor/policies/neutron-teams
writing output... [ 73%] contributor/policies/release-checklist
writing output... [ 74%] contributor/policies/thirdparty-ci
writing output... [ 74%] contributor/stadium/governance
writing output... [ 74%] contributor/stadium/guidelines
writing output... [ 75%] contributor/stadium/index
writing output... [ 75%] contributor/testing/ci_scenario_jobs
writing output... [ 76%] contributor/testing/coverage
writing output... [ 76%] contributor/testing/db_transient_failure_injection
writing output... [ 76%] contributor/testing/fullstack
writing output... [ 77%] contributor/testing/index
writing output... [ 77%] contributor/testing/ovn_devstack
writing output... [ 77%] contributor/testing/tempest
writing output... [ 78%] contributor/testing/template_model_sync_test
writing output... [ 78%] contributor/testing/testing
writing output... [ 78%] contributor/upgrade_checks
writing output... [ 79%] feature_classification/feature_classification_introduction
writing output... [ 79%] feature_classification/general_feature_support_matrix
writing output... [ 80%] feature_classification/index
writing output... [ 80%] feature_classification/provider_network_support_matrix
writing output... [ 80%] index
writing output... [ 81%] install/common/get-started-networking
writing output... [ 81%] install/compute-install-obs
writing output... [ 81%] install/compute-install-option1-obs
writing output... [ 82%] install/compute-install-option1-rdo
writing output... [ 82%] install/compute-install-option1-ubuntu
writing output... [ 83%] install/compute-install-option2-obs
writing output... [ 83%] install/compute-install-option2-rdo
writing output... [ 83%] install/compute-install-option2-ubuntu
writing output... [ 84%] install/compute-install-rdo
writing output... [ 84%] install/compute-install-ubuntu
writing output... [ 84%] install/concepts
writing output... [ 85%] install/controller-install-obs
writing output... [ 85%] install/controller-install-option1-obs
writing output... [ 85%] install/controller-install-option1-rdo
writing output... [ 86%] install/controller-install-option1-ubuntu
writing output... [ 86%] install/controller-install-option2-obs
writing output... [ 87%] install/controller-install-option2-rdo
writing output... [ 87%] install/controller-install-option2-ubuntu
writing output... [ 87%] install/controller-install-rdo
writing output... [ 88%] install/controller-install-ubuntu
writing output... [ 88%] install/environment-networking-compute-obs
writing output... [ 88%] install/environment-networking-compute-rdo
writing output... [ 89%] install/environment-networking-compute-ubuntu
writing output... [ 89%] install/environment-networking-controller-obs
writing output... [ 90%] install/environment-networking-controller-rdo
writing output... [ 90%] install/environment-networking-controller-ubuntu
writing output... [ 90%] install/environment-networking-obs
writing output... [ 91%] install/environment-networking-rdo
writing output... [ 91%] install/environment-networking-storage-cinder
writing output... [ 91%] install/environment-networking-ubuntu
writing output... [ 92%] install/environment-networking-verify-obs
writing output... [ 92%] install/environment-networking-verify-rdo
writing output... [ 92%] install/environment-networking-verify-ubuntu
writing output... [ 93%] install/index
writing output... [ 93%] install/install-obs
writing output... [ 94%] install/install-rdo
writing output... [ 94%] install/install-ubuntu
writing output... [ 94%] install/overview
writing output... [ 95%] install/ovn/index
writing output... [ 95%] install/ovn/manual_install
writing output... [ 95%] install/ovn/tripleo_install
writing output... [ 96%] install/shared/note_configuration_vary_by_distribution
writing output... [ 96%] install/verify
writing output... [ 97%] install/verify-option1
writing output... [ 97%] install/verify-option2
writing output... [ 97%] ovn/dhcp_opts
writing output... [ 98%] ovn/faq/index
writing output... [ 98%] ovn/gaps
writing output... [ 98%] ovn/index
writing output... [ 99%] ovn/migration
writing output... [ 99%] pdf-index
writing output... [100%] reference/rest-api

generating indices... genindex py-modindex [openstackdocstheme] could not determine last_updated for 'py-modindex'
done
writing additional pages... search done
copying images... [  1%] admin/archives/figures/vmware_nsx_ex1.png
copying images... [  2%] admin/archives/figures/vmware_nsx_ex2.png
copying images... [  4%] admin/figures/bgp-dynamic-routing-overview.png
copying images... [  5%] admin/figures/bgp-dynamic-routing-example1.png
copying images... [  7%] admin/figures/bgp-dynamic-routing-example2.png
copying images... [  8%] admin/figures/bgp-floating-ip-over-l2-segmented-network.png
copying images... [ 10%] admin/figures/demo_multiple_dhcp_agents.png
copying images... [ 11%] admin/figures/logging-framework.png
copying images... [ 13%] admin/figures/config-macvtap-compute1.png
copying images... [ 14%] admin/figures/config-macvtap-compute2.png
copying images... [ 15%] admin/figures/port-chain-architecture-diagram.png
copying images... [ 17%] admin/figures/port-chain-diagram.png
copying images... [ 18%] admin/figures/deploy-lb-ha-vrrp-overview.png
copying images... [ 20%] admin/figures/deploy-lb-ha-vrrp-compconn1.png
copying images... [ 21%] admin/figures/deploy-lb-provider-overview.png
copying images... [ 23%] admin/figures/deploy-lb-provider-compconn1.png
copying images... [ 24%] admin/figures/deploy-lb-provider-compconn2.png
copying images... [ 26%] admin/figures/deploy-lb-provider-flowns1.png
copying images... [ 27%] admin/figures/deploy-lb-provider-flowew1.png
copying images... [ 28%] admin/figures/deploy-lb-provider-flowew2.png
copying images... [ 30%] admin/figures/deploy-lb-selfservice-overview.png
copying images... [ 31%] admin/figures/deploy-lb-selfservice-compconn1.png
copying images... [ 33%] admin/figures/deploy-lb-selfservice-flowns1.png
copying images... [ 34%] admin/figures/deploy-lb-selfservice-flowns2.png
copying images... [ 36%] admin/figures/deploy-lb-selfservice-flowew1.png
copying images... [ 37%] admin/figures/deploy-lb-selfservice-flowew2.png
copying images... [ 39%] admin/figures/deploy-ovs-ha-dvr-overview.png
copying images... [ 40%] admin/figures/deploy-ovs-ha-dvr-compconn1.png
copying images... [ 42%] admin/figures/deploy-ovs-ha-dvr-flowns1.png
copying images... [ 43%] admin/figures/deploy-ovs-ha-dvr-flowns2.png
copying images... [ 44%] admin/figures/deploy-ovs-ha-dvr-flowew1.png
copying images... [ 46%] admin/figures/deploy-ovs-ha-vrrp-overview.png
copying images... [ 47%] admin/figures/deploy-ovs-ha-vrrp-compconn1.png
copying images... [ 49%] admin/figures/deploy-ovs-provider-overview.png
copying images... [ 50%] admin/figures/deploy-ovs-provider-compconn1.png
copying images... [ 52%] admin/figures/deploy-ovs-provider-compconn2.png
copying images... [ 53%] admin/figures/deploy-ovs-provider-flowns1.png
copying images... [ 55%] admin/figures/deploy-ovs-provider-flowew1.png
copying images... [ 56%] admin/figures/deploy-ovs-provider-flowew2.png
copying images... [ 57%] admin/figures/deploy-ovs-selfservice-overview.png
copying images... [ 59%] admin/figures/deploy-ovs-selfservice-compconn1.png
copying images... [ 60%] admin/figures/deploy-ovs-selfservice-flowns1.png
copying images... [ 62%] admin/figures/deploy-ovs-selfservice-flowns2.png
copying images... [ 63%] admin/figures/deploy-ovs-selfservice-flowew1.png
copying images... [ 65%] admin/figures/deploy-ovs-selfservice-flowew2.png
copying images... [ 66%] admin/figures/NetworkTypes.png
copying images... [ 68%] admin/ovn/refarch/figures/ovn-hw.png
copying images... [ 69%] admin/ovn/refarch/figures/ovn-services.png
copying images... [ 71%] admin/ovn/refarch/figures/ovn-architecture1.png
copying images... [ 72%] admin/ovn/refarch/figures/ovn-compute1.png
copying images... [ 73%] admin/ovn/figures/ovn-north-south.png
copying images... [ 75%] admin/ovn/figures/ovn-north-south-distributed-fip.png
copying images... [ 76%] admin/ovn/figures/ovn-l3ha-bfd.png
copying images... [ 78%] admin/ovn/figures/ovn-l3ha-bfd-3gw.png
copying images... [ 79%] admin/ovn/figures/ovn-l3ha-bfd-failover.png
copying images... [ 81%] admin/ovn/figures/ovn-east-west-3.png
copying images... [ 82%] admin/ovn/figures/ovn-east-west-2.png
copying images... [ 84%] contributor/internals/images/under-the-hood-scenario-1-ovs-network.png
copying images... [ 85%] contributor/internals/images/under-the-hood-scenario-1-ovs-netns.png
copying images... [ 86%] contributor/internals/images/live-mig.png
copying images... [ 88%] contributor/internals/images/live-mig-ovs-hybrid.png
copying images... [ 89%] contributor/internals/images/under-the-hood-scenario-1-ovs-compute.png
copying images... [ 91%] contributor/testing/images/fullstack_multinode_simulation.png
copying images... [ 92%] install/figures/networklayout.png
copying images... [ 94%] install/figures/hwreqs.png
copying images... [ 95%] install/figures/network1-services.png
copying images... [ 97%] install/figures/network2-services.png
copying images... [ 98%] install/ovn/figures/tripleo-ovn-arch.png
copying images... [100%] install/ovn/figures/ovn-initial-resources.png

copying downloadable files... [100%] ../_static/neutron.policy.yaml.sample

copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in doc/build/html.
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
  docs: commands succeeded
  congratulations :)

```

**Comment by ralonsoh** [comment]
Hi @svinota. That usually happens when you reinstall the requirements. But any other installed library (mitogen) from any previous execution, will be still there.

When testing, I usually delete the .tox directory to remove any existing requirements installation. Every time I re-execute the test without any previous directory in place.

**Comment by svinota** [comment]
>  I usually delete the .tox directory to remove any existing requirements installation

So do I. The test is done in a fresh VM, w/o any previous tox cache, without extra python modules installed.

After the run there is no mitogen in the `.tox`. The run succeeds without the mitogen dependency declared in `tox.ini` and with `pyroute.*-0.6.2`. And I double-checked it fails with `pyroute.*-0.6.1`.

**Comment by ralonsoh** [comment]
Ok, I think my upper-constraints file was incorrect: I was changing only pyroute2, but not all submodules upper versions (e.g.: https://review.opendev.org/c/openstack/requirements/+/793102/2/upper-constraints.txt).

I've tested with the updated one, bumping all modules version, and now it's working.

As usual, thanks a lot for your efforts!

**Comment by svinota** [comment]
So I close the issue. Thanks!
